services:
  # NestJS Application (conectando ao Supabase externo)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: onterapi-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Force IPv4
      NODE_OPTIONS: "--dns-result-order=ipv4first"
      # Swagger configuration for Docker
      SWAGGER_SERVER_URL: "http://localhost:3001"
    ports:
      - "3001:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "ogffdaemylaezxpunmop.supabase.co:104.18.38.10"
      - "aws-0-sa-east-1.pooler.supabase.com:54.94.90.106"
      - "smtp.ethereal.email:95.216.108.161"
    networks:
      - onterapi-network
    volumes:
      - /app/node_modules # Prevent overwriting node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  onterapi-network:
    driver: bridge