export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRES_IN: 900,
  REFRESH_TOKEN_EXPIRES_DAYS: 7,
  REFRESH_TOKEN_TRUSTED_EXPIRES_DAYS: 30,
  TWO_FACTOR_CODE_EXPIRES_MINUTES: 5,
  TWO_FACTOR_MAX_ATTEMPTS: 3,
  TEMP_TOKEN_EXPIRES_MINUTES: 10,
  PASSWORD_MIN_LENGTH: 8,
  EMAIL_VERIFICATION_LINK_EXPIRES_MINUTES: 60,
  PASSWORD_RESET_LINK_EXPIRES_MINUTES: 60,
  FAILED_LOGIN_LOCK_MINUTES: 30,

  DEFAULT_ROLE: 'PATIENT',

  DEFAULT_VALUES: {
    DEVICE: 'Dispositivo desconhecido',
    IP: 'IP nao disponivel',
    LOCATION: 'Localizacao nao disponivel',
    USER_AGENT: 'Navegador nao identificado',
  },
} as const;

export const AUTH_MESSAGES = {
  ERRORS: {
    INVALID_CREDENTIALS: 'Credenciais invalidas',
    WEAK_PASSWORD: 'Senha nao atende aos requisitos minimos de seguranca',
    INVALID_TOKEN: 'Token invalido ou expirado',
    EXPIRED_TOKEN: 'Token expirado',
    INVALID_TEMPORARY_TOKEN: 'Token temporario invalido',
    INVALID_RESET_TOKEN: 'Token de reset invalido ou expirado',
    VERIFICATION_TOKEN_INVALID: 'Token de verificacao invalido ou expirado',
    TEST_TOKEN_INVALID: 'Token de teste nao valido',
    TOKEN_NOT_PROVIDED: 'Token nao fornecido',
    USER_NOT_FOUND: 'Usuario nao encontrado',
    USER_ID_NOT_FOUND: 'ID do usuario nao encontrado',
    USER_ALREADY_EXISTS: 'Usuario ja existe',
    EMAIL_ALREADY_EXISTS: 'Email ja cadastrado no sistema',
    USER_NOT_AUTHENTICATED: 'Usuario nao autenticado',
    USER_NOT_FOUND_AFTER_UPDATE: 'Usuario nao encontrado apos atualizacao',
    ACCOUNT_DISABLED: 'Conta desativada',
    ACCOUNT_LOCKED: 'Conta bloqueada temporariamente',
    EMAIL_NOT_VERIFIED: 'Email nao verificado. Por favor, verifique seu email primeiro.',
    SESSION_EXPIRED: 'Sessao expirada',
    SESSION_NOT_FOUND: 'Sessao nao encontrada',
    TWO_FA_REQUIRED: 'Autenticacao de dois fatores necessaria',
    INVALID_CODE: 'Codigo invalido',
    INVALID_2FA_CODE: 'Codigo 2FA invalido',
    INSUFFICIENT_PERMISSION: 'Permissao insuficiente para esta operacao',
    TENANT_ACCESS_DENIED: 'Acesso negado a este tenant',
    ROLE_NOT_ALLOWED: 'Role nao permitida para esta operacao',
    TOO_MANY_ATTEMPTS: 'Muitas tentativas. Tente novamente mais tarde.',
    MAX_ATTEMPTS_EXCEEDED: 'Numero maximo de tentativas excedido',
    EMAIL_SEND_ERROR: 'Erro ao enviar email. Por favor, tente novamente.',
    CREATE_USER_ERROR: 'Erro ao criar usuario',
    UPDATE_USER_ERROR: 'Erro ao atualizar usuario',
    DELETE_USER_ERROR: 'Erro ao deletar usuario',
    SUPABASE_ERROR: 'Erro ao comunicar com Supabase',
    METHOD_NOT_IMPLEMENTED: 'Metodo nao implementado',
    INTERNAL_ERROR: 'Erro interno do servidor',
  },

  SUCCESS: {
    LOGIN: 'Login realizado com sucesso',
    LOGOUT: 'Logout realizado com sucesso',
    LOGOUT_ALL_DEVICES: 'Logout realizado em todos os dispositivos',
    TOKEN_REFRESHED: 'Token renovado com sucesso',
    TWO_FA_SENT: 'Codigo 2FA enviado com sucesso',
    TWO_FA_VALIDATED: '2FA validado com sucesso',
    TWO_FA_ENABLED: '2FA habilitado com sucesso',
    TWO_FA_DISABLED: '2FA desabilitado com sucesso',
    EMAIL_SENT: 'Email enviado com sucesso',
    EMAIL_VERIFIED: 'Email verificado com sucesso! Voce ja pode fazer login.',
    VERIFICATION_EMAIL_SENT: 'Email de verificacao enviado',
    RESET_EMAIL_SENT: 'Email de recuperacao de senha enviado',
    USER_CREATED: 'Usuario criado com sucesso',
    USER_UPDATED: 'Usuario atualizado com sucesso',
    USER_DELETED: 'Usuario deletado com sucesso',
    PASSWORD_RESET: 'Senha redefinida com sucesso',
    PASSWORD_CHANGED: 'Senha alterada com sucesso',
  },

  INFO: {
    TWO_FA_REQUIRED: 'Autenticacao de dois fatores requerida. Por favor, insira o codigo.',
    CHECK_EMAIL: 'Por favor, verifique seu email para continuar.',
    SESSION_ACTIVE: 'Sessao ativa',
  },
} as const;

export const AUTH_PATTERNS = {
  EMAIL_SPLIT_CHAR: '@',
  EMAIL_MASK_CHAR: '*',
} as const;
