export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRES_IN: 900,
  REFRESH_TOKEN_EXPIRES_DAYS: 7,
  REFRESH_TOKEN_TRUSTED_EXPIRES_DAYS: 30,
  TWO_FACTOR_CODE_EXPIRES_MINUTES: 5,
  TWO_FACTOR_MAX_ATTEMPTS: 3,
  TEMP_TOKEN_EXPIRES_MINUTES: 10,
  PASSWORD_MIN_LENGTH: 8,
  EMAIL_VERIFICATION_LINK_EXPIRES_MINUTES: 60,
  PASSWORD_RESET_LINK_EXPIRES_MINUTES: 60,
  FAILED_LOGIN_LOCK_MINUTES: 30,

  DEFAULT_ROLE: 'PATIENT',

  DEFAULT_VALUES: {
    DEVICE: 'Dispositivo desconhecido',
    IP: 'IP não disponível',
    LOCATION: 'Localização não disponível',
    USER_AGENT: 'Navegador não identificado',
  },
} as const;

export const AUTH_MESSAGES = {
  ERRORS: {
    INVALID_CREDENTIALS: 'Credenciais inválidas',
    WEAK_PASSWORD: 'Senha não atende aos requisitos mínimos de segurança',
    INVALID_TOKEN: 'Token inválido ou expirado',
    EXPIRED_TOKEN: 'Token expirado',
    INVALID_TEMPORARY_TOKEN: 'Token temporário inválido',
    INVALID_RESET_TOKEN: 'Token de reset inválido ou expirado',
    VERIFICATION_TOKEN_INVALID: 'Token de verificação inválido ou expirado',
    TEST_TOKEN_INVALID: 'Token de teste não é válido',
    TOKEN_NOT_PROVIDED: 'Token não fornecido',
    USER_NOT_FOUND: 'Usuário não encontrado',
    USER_ID_NOT_FOUND: 'ID do usuário não encontrado',
    USER_ALREADY_EXISTS: 'Usuário já existe',
    EMAIL_ALREADY_EXISTS: 'Email já cadastrado no sistema',
    USER_NOT_AUTHENTICATED: 'Usuário não autenticado',
    USER_NOT_FOUND_AFTER_UPDATE: 'Usuário não encontrado após atualização',
    ACCOUNT_DISABLED: 'Conta desativada',
    ACCOUNT_LOCKED: 'Conta bloqueada temporariamente',
    EMAIL_NOT_VERIFIED: 'Email não verificado. Por favor, verifique seu email primeiro.',
    SESSION_EXPIRED: 'Sessão expirada',
    SESSION_NOT_FOUND: 'Sessão não encontrada',
    TWO_FA_REQUIRED: 'Autenticação de dois fatores necessária',
    INVALID_CODE: 'Código inválido',
    INVALID_2FA_CODE: 'Código 2FA inválido',
    INSUFFICIENT_PERMISSION: 'Permissão insuficiente para esta operação',
    TENANT_ACCESS_DENIED: 'Acesso negado a este tenant',
    ROLE_NOT_ALLOWED: 'Role não permitida para esta operação',
    TOO_MANY_ATTEMPTS: 'Muitas tentativas. Tente novamente mais tarde.',
    MAX_ATTEMPTS_EXCEEDED: 'Número máximo de tentativas excedido',
    EMAIL_SEND_ERROR: 'Erro ao enviar email. Por favor, tente novamente.',
    CREATE_USER_ERROR: 'Erro ao criar usuário',
    UPDATE_USER_ERROR: 'Erro ao atualizar usuário',
    DELETE_USER_ERROR: 'Erro ao deletar usuário',
    SUPABASE_ERROR: 'Erro ao comunicar com Supabase',
    METHOD_NOT_IMPLEMENTED: 'Método não implementado',
    INTERNAL_ERROR: 'Erro interno do servidor',
  },

  SUCCESS: {
    LOGIN: 'Login realizado com sucesso',
    LOGOUT: 'Logout realizado com sucesso',
    LOGOUT_ALL_DEVICES: 'Logout realizado em todos os dispositivos',
    TOKEN_REFRESHED: 'Token renovado com sucesso',
    TWO_FA_SENT: 'Código 2FA enviado com sucesso',
    TWO_FA_VALIDATED: '2FA validado com sucesso',
    TWO_FA_ENABLED: '2FA habilitado com sucesso',
    TWO_FA_DISABLED: '2FA desabilitado com sucesso',
    EMAIL_SENT: 'Email enviado com sucesso',
    EMAIL_VERIFIED: 'Email verificado com sucesso! Você já pode fazer login.',
    VERIFICATION_EMAIL_SENT: 'Email de verificação enviado',
    RESET_EMAIL_SENT: 'Email de recuperação de senha enviado',
    USER_CREATED: 'Usuário criado com sucesso',
    USER_UPDATED: 'Usuário atualizado com sucesso',
    USER_DELETED: 'Usuário deletado com sucesso',
    PASSWORD_RESET: 'Senha redefinida com sucesso',
    PASSWORD_CHANGED: 'Senha alterada com sucesso',
  },

  INFO: {
    TWO_FA_REQUIRED: 'Autenticação de dois fatores requerida. Por favor, insira o código.',
    CHECK_EMAIL: 'Por favor, verifique seu email para continuar.',
    SESSION_ACTIVE: 'Sessão ativa',
  },
} as const;

export const AUTH_PATTERNS = {
  EMAIL_SPLIT_CHAR: '@',
  EMAIL_MASK_CHAR: '*',
} as const;
