export const ERROR_CODES = {
  AUTH: {
    INVALID_CREDENTIALS: 'AUTH001',
    INVALID_TOKEN: 'AUTH002',
    EXPIRED_TOKEN: 'AUTH003',
    TOKEN_NOT_PROVIDED: 'AUTH004',
    USER_NOT_AUTHENTICATED: 'AUTH005',
    EMAIL_NOT_VERIFIED: 'AUTH006',
    ACCOUNT_DISABLED: 'AUTH007',
    ACCOUNT_LOCKED: 'AUTH008',
    INSUFFICIENT_PERMISSIONS: 'AUTH009',
    ACCESS_DENIED: 'AUTH010',
    SESSION_EXPIRED: 'AUTH011',
    INVALID_2FA_CODE: 'AUTH012',
    TWO_FACTOR_REQUIRED: 'AUTH013',
    TOO_MANY_ATTEMPTS: 'AUTH014',
  },

  USER: {
    NOT_FOUND: 'USER001',
    ALREADY_EXISTS: 'USER002',
    EMAIL_IN_USE: 'USER003',
    CPF_IN_USE: 'USER004',
    INVALID_DATA: 'USER005',
    UPDATE_FAILED: 'USER006',
    DELETE_FAILED: 'USER007',
    CREATION_FAILED: 'USER008',
  },

  VALIDATION: {
    REQUIRED_FIELD: 'VAL001',
    INVALID_FORMAT: 'VAL002',
    OUT_OF_RANGE: 'VAL003',
    TYPE_MISMATCH: 'VAL004',
    CONSTRAINT_VIOLATION: 'VAL005',
  },

  SYSTEM: {
    INTERNAL_ERROR: 'SYS001',
    SERVICE_UNAVAILABLE: 'SYS002',
    DATABASE_ERROR: 'SYS003',
    EXTERNAL_SERVICE_ERROR: 'SYS004',
    CONFIGURATION_ERROR: 'SYS005',
    NOT_IMPLEMENTED: 'SYS006',
  },

  BUSINESS: {
    OPERATION_NOT_ALLOWED: 'BUS001',
    INVALID_STATE: 'BUS002',
    LIMIT_EXCEEDED: 'BUS003',
    RESOURCE_LOCKED: 'BUS004',
    DUPLICATE_OPERATION: 'BUS005',
  },
};

export const ERROR_MESSAGES = {
  DEFAULT: 'Ocorreu um erro inesperado',
  TRY_AGAIN: 'Por favor, tente novamente',
  CONTACT_SUPPORT: 'Se o problema persistir, entre em contato com o suporte',
  INVALID_REQUEST: 'Requisição inválida',
  NOT_FOUND: 'Recurso não encontrado',
  UNAUTHORIZED: 'Não autorizado',
  FORBIDDEN: 'Acesso negado',
  CONFLICT: 'Conflito na operação',
  UNPROCESSABLE: 'Não foi possível processar a requisição',
};
